spring:
  application:
    name: "SpringRedis"
  datasource:
    url: jdbc:mysql://localhost:5306/persondb
    username: root
    password: dbadmin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  main:
    allow-bean-definition-overriding: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379


server:
  port: 5000
